modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="planetary"
version="2.0.0-alpha.1"
displayName="Planetary"
description='''Finite cube-planet world topology for Minecraft.'''

[[dependencies.planetary]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.planetary]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"
